spring.application.name=transaction-service

logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN
