spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frauddb
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate